table 'Product Subcategories Lookup'
	lineageTag: 008d1b89-9bcf-42fc-a9d6-30a0808dcc1c

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 2e4c7b09-aa46-4d54-a0f8-345ee2ac4569
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column SubcategoryName
		dataType: string
		lineageTag: 607fc353-dda2-4c57-a65c-364f2c1442db
		summarizeBy: none
		sourceColumn: SubcategoryName

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: eb8f1223-23a8-431e-aeae-e013c49da289
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	partition 'Product Subcategories Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\rokib.hasan\Documents\Work\Learning\AdventureWorks-Internet-Sales-Analytics-main (1)\AdventureWorks-Internet-Sales-Analytics-main\AdventureWorks Product Subcategories Lookup.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductSubcategoryKey", Int64.Type}, {"SubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

