table 'Returns Data'
	lineageTag: a37dc88c-a442-4486-b0f9-10a6a0be1e83

	measure 'Total Value of Returns' = SUMX('Returns Data', 'Returns Data'[ReturnQuantity] * RELATED('Product Lookup'[ProductPrice]))
		lineageTag: 4aa78e3e-3954-449a-9165-9c8f38fd09ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Return Cost Impact' = SUMX('Returns Data', 'Returns Data'[ReturnQuantity] * RELATED('Product Lookup'[ProductCost]))
		lineageTag: b394894e-9334-46b8-8607-33d1db9bbcfb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Profit Loss' = [Total Value of Returns] - [Return Cost Impact]
		lineageTag: faf1f276-9d3e-426e-af13-edd6a9d21b17

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Profit' = [Gross Profit] - [Net Profit Loss]
		lineageTag: ea2390cf-1140-4ed0-83df-5120d3163bea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ReturnDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4254348-0d34-4961-a00e-34adfe402cea
		summarizeBy: none
		sourceColumn: ReturnDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: ccbe4d90-0ac8-419b-8c46-a975737fdad8
		summarizeBy: count
		sourceColumn: TerritoryKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: aa11c173-a576-4558-a706-b0f45202d73d
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: 2f64878a-9168-4ae5-849e-35f590c3b14e
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		annotation SummarizationSetBy = Automatic

	partition 'Returns Data' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\rokib.hasan\Documents\Work\Learning\AdventureWorks-Internet-Sales-Analytics-main (1)\AdventureWorks-Internet-Sales-Analytics-main\AdventureWorks Returns Data.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ReturnDate", type date}, {"TerritoryKey", Int64.Type}, {"ProductKey", Int64.Type}, {"ReturnQuantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

